Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/alguien/.local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/alguien/Bot_Python/commands/utility/utility.py", line 46, in on_message
    return await experiencia(message)
  File "/home/alguien/Bot_Python/commands/utility/commands/exp.py", line 65, in experiencia
    doc_ref.update({'meta': int(current_meta['id'])})
TypeError: 'NoneType' object is not subscriptable
